server:
  port: 8814
  ssl:
    enabled: true
    key-store: keystore.p12
    key-store-type: PKCS12
    key-store-password: password

spring:
  data:
    jdbc:
      dialect: h2
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/lunch
    username: seungpro
    password: seungpro
  jpa:
    database-platform: org.hibernate.dialect.
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
