server:
  port: 8814
  ssl:
    enabled: true
    key-store: keystore.p12
    key-store-type: PKCS12
    key-store-password: password

spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  profiles:
    active: dev
