spring:
  data:
    jdbc:
      dialect: h2
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/Workspace/DB/lunch
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        show_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console