server:
  port: ${SERVER_PORT:8814}
  ssl:
    enabled: ${SSL_ENABLED:true}
    key-store: ${SSL_KEY_STORE:keystore.p12}
    key-store-type: ${SSL_KEY_STORE_TYPE:PKCS12}
    key-store-password: ${SSL_KEY_STORE_PASSWORD:password}

spring:
  jpa:
    hibernate:
      ddl-auto: none
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

works:
  auth:
    baseUrl: ${WORKS_AUTH_BASE_URL:https://auth.worksmobile.com/oauth2/v2.0/}
    grantType: ${WORKS_GRANT_TYPE:urn:ietf:params:oauth:grant-type:jwt-bearer}
    clientId: ${WORKS_CLIENT_ID:K2QyhD6NCeYhwynPBicm}
    clientSecret: ${WORKS_CLIENT_SECRET:XbNeeMRUSl}
    scope: ${WORKS_SCOPE:bot bot.message bot.read user}
    serviceAccount: ${WORKS_SERVICE_ACCOUNT:gk8ez.serviceaccount@k2systems.kr}
  api:
    baseUrl: ${WORKS_API_BASE_URL:https://www.worksapis.com/v1.0/}
    botId: ${WORKS_BOT_ID:9145405}

jwt:
  privateKeyPath: ${JWT_PRIVATE_KEY_PATH:keys/works_private.key}
  expiration_time: ${JWT_EXPIRATION_TIME:180}